pools:
  - id: HTTP pool
    gun:
      type: http/scenario
      target: petstore.swagger.io:443
      answlog:
        enabled: true
        path: ./answ.log
        filter: all
      ssl: true
    ammo:
      type: http/scenario
      file: ./scenarios/ammos/ammo.yaml
    result:
      type: phout
      destination: ./phout.log
    rps:
      - {duration: 5s, type: const, ops: 5}
    startup:
      - type: once
        times: 10000
